### ISSUE TITLE
Single line incrrect

### ISSUE THREAD

**Issue by NightMigera** [yanni4night/node-ssi#12]
if file contains ''
includeFileReg exec two expression as one
For fix need  change
```var includeFileReg = /<!--#\s*include\s+(file|virtual)=(['"])([^\r\n\s]+?)\2\s*(.*)-->/;```

to

```var includeFileReg = /<!--#\s*include\s+(file|virtual)=(['"])([^\r\n\s]+?)\2\s*(.*?)-->/;```

**Comment by yanni4night** [comment]
Fixed and tested, thanks!
