### ISSUE TITLE
"virtual" should specifies the target relative to the domain root

### ISSUE THREAD

**Issue by kidwm** [yanni4night/node-ssi#2]
According the spec on Wikipedia:
http://en.wikipedia.org/wiki/Server_Side_Includes

It seems wrong in the note of current readme file.

**Comment by jbouzekri** [comment]
Hi,
I am interested with this change. Will you be able to start development again on it ?
Thanks

**Comment by jbouzekri** [comment]
I have made a pull request on this point : #7 
If it is okay, could you merge and make a new release ?

**Comment by nfriedly** [comment]
Op, sorry I never got back to this, I took a glance at the PR and it looks good to me. Want to merge it @yanni4night ?
