### ISSUE TITLE
Create a basic example app for README?

### ISSUE THREAD

**Issue by taoeffect** [yanni4night/node-ssi#5]
If I'm understanding correctly, the example given in the current README doesn't actually show how to quickly run a server with this.

Can you post simple example code that can be used to simply server pages in a folder?

For example, I'd like to be able to run `node index.js` from a directory containing an `index.html` file and for that to immediately start a server on `localhost:8080` serving that file (and any other linked images, sub-links, SSI includes, etc.) automatically (for developing locally without having to install nginx on a dev machine).

**Comment by taoeffect** [comment]
I went ahead and created it for okturtles.com.

[BEHOLD!](https://github.com/okTurtles/okturtles.com/blob/4050f04d8f5250be0db98edc2c4ce8d520f39ea8/server.coffee)

It runs great! Thanks so much for this library! :smile: :+1:

**Comment by taoeffect** [comment]
Another example for serving files using `grunt-contrib-connect`:

```javascript
    connect: { // https://github.com/gruntjs/grunt-contrib-connect
      options: {
        port: 8000,
        base: 'dist',
        livereload: true,
        middleware: (connect, opts, middlewares) => {
          middlewares.unshift((req, res, next) => {
            var f = url.parse(req.url).pathname
            f = path.join('dist', S(f).endsWith('/') ? f + 'index.html' : f)
            // grunt.log.writeln(`request for: ${req.url}`)
            if (S(f).endsWith('.html') && fs.existsSync(f)) {
              ssi.compileFile(f, (err, content) => {
                if (err) {
                  console.error(err.stack)
                  throw err
                }
                console.log(`Req: ${req.url} => sending node-ssi parsed file: ${f}`)
                res.end(content)
              })
            } else {
              next()
            }
          })
          return middlewares
        }
      },
      dev: {}
    }
```

**Comment by yanni4night** [comment]
Thanks for your work! I will start and keep improving this repo later
